theme = "tokyonight_moon"
[editor]
cursorline = true
bufferline = "always"
color-modes = true

[editor.lsp]
display-inlay-hints = true
# display-massages = false

[keys.insert]
j = { k = "normal_mode" }
